- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.0-rc5"
}
```
> chore(cd): update Spinnaker version to 2.27.0-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.0-rc6"
}
```
> chore(cd): update Spinnaker version to 2.27.0-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.0-rc7"
}
```
> chore(cd): update Spinnaker version to 2.27.0-rc7

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.0"
}
```
> chore(cd): update Spinnaker version to 2.27.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.1-rc5"
}
```
> chore(cd): update Spinnaker version to 2.27.1-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.1-rc6"
}
```
> chore(cd): update Spinnaker version to 2.27.1-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.1-rc7"
}
```
> chore(cd): update Spinnaker version to 2.27.1-rc7

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.1-rc8"
}
```
> chore(cd): update Spinnaker version to 2.27.1-rc8

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.1"
}
```
> chore(cd): update Spinnaker version to 2.27.1

- .github/workflows/update-patch-version.yml
The last merge I did I removed the double quote accidentally.
> fix(patches): add double quote removed by merge

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc1"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc2"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc3"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc4"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc5"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3-rc6"
}
```
> chore(cd): update Spinnaker version to 2.27.3-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.3"
}
```
> chore(cd): update Spinnaker version to 2.27.3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc5"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc6"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc8"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc8

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0-rc9"
}
```
> chore(cd): update Spinnaker version to 2.28.0-rc9

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.0"
}
```
> chore(cd): update Spinnaker version to 2.28.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.1-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.1-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.1-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.1-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.1-rc3"
}
```
> chore(cd): update Spinnaker version to 2.28.1-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.1-rc4"
}
```
> chore(cd): update Spinnaker version to 2.28.1-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.1"
}
```
> chore(cd): update Spinnaker version to 2.28.1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.2-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.2-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.2-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.2-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.2-rc3"
}
```
> chore(cd): update Spinnaker version to 2.28.2-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.2"
}
```
> chore(cd): update Spinnaker version to 2.28.2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.3-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.3-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.3-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.3-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.3"
}
```
> chore(cd): update Spinnaker version to 2.28.3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.4-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.4-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.4"
}
```
> chore(cd): update Spinnaker version to 2.28.4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.5-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.5-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.5-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.5-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.5-rc3"
}
```
> chore(cd): update Spinnaker version to 2.28.5-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.7"
}
```
> chore(cd): update Spinnaker version to 2.27.7

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.27.5"
}
```
> chore(cd): update Spinnaker version to 2.27.5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.5"
}
```
> chore(cd): update Spinnaker version to 2.28.5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.6-rc1"
}
```
> chore(cd): update Spinnaker version to 2.28.6-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.6-rc2"
}
```
> chore(cd): update Spinnaker version to 2.28.6-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.28.6"
}
```
> chore(cd): update Spinnaker version to 2.28.6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc4"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc5"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc6"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc7"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc7

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0"
}
```
> chore(cd): update Spinnaker version to 2.30.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc8"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc8

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.0-rc9"
}
```
> chore(cd): update Spinnaker version to 2.30.0-rc9

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.1-rc1"
}
```
> chore(cd): update Spinnaker version to 2.30.1-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.1-rc2"
}
```
> chore(cd): update Spinnaker version to 2.30.1-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.1"
}
```
> chore(cd): update Spinnaker version to 2.30.1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.2-rc1"
}
```
> chore(cd): update Spinnaker version to 2.30.2-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.2"
}
```
> chore(cd): update Spinnaker version to 2.30.2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.3"
}
```
> chore(cd): update Spinnaker version to 2.30.3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.3-rc1"
}
```
> chore(cd): update Spinnaker version to 2.30.3-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.31.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.31.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.31.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.31.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.4"
}
```
> chore(cd): update Spinnaker version to 2.30.4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.30.5"
}
```
> chore(cd): update Spinnaker version to 2.30.5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.31.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.31.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.31.0"
}
```
> chore(cd): update Spinnaker version to 2.31.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.32.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.32.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.32.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.0-rc4"
}
```
> chore(cd): update Spinnaker version to 2.32.0-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.0"
}
```
> chore(cd): update Spinnaker version to 2.32.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.1-rc1"
}
```
> chore(cd): update Spinnaker version to 2.32.1-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.1-rc2"
}
```
> chore(cd): update Spinnaker version to 2.32.1-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.1-rc3"
}
```
> chore(cd): update Spinnaker version to 2.32.1-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2-rc2"
}
```
> chore(cd): update Spinnaker version to 2.32.2-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2-rc3"
}
```
> chore(cd): update Spinnaker version to 2.32.2-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2-rc4"
}
```
> chore(cd): update Spinnaker version to 2.32.2-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2-rc5"
}
```
> chore(cd): update Spinnaker version to 2.32.2-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2-rc6"
}
```
> chore(cd): update Spinnaker version to 2.32.2-rc6

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.2"
}
```
> chore(cd): update Spinnaker version to 2.32.2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.3-rc2"
}
```
> chore(cd): update Spinnaker version to 2.32.3-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.3-rc3"
}
```
> chore(cd): update Spinnaker version to 2.32.3-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.32.3"
}
```
> chore(cd): update Spinnaker version to 2.32.3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.34.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.34.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.34.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.34.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.34.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.34.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.34.0"
}
```
> chore(cd): update Spinnaker version to 2.34.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.34.1-rc1"
}
```
> chore(cd): update Spinnaker version to 2.34.1-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0-rc1"
}
```
> chore(cd): update Spinnaker version to 2.36.0-rc1

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0-rc2"
}
```
> chore(cd): update Spinnaker version to 2.36.0-rc2

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.35.0"
}
```
> chore(cd): update Spinnaker version to 2.35.0

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0-rc3"
}
```
> chore(cd): update Spinnaker version to 2.36.0-rc3

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0-rc4"
}
```
> chore(cd): update Spinnaker version to 2.36.0-rc4

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0-rc5"
}
```
> chore(cd): update Spinnaker version to 2.36.0-rc5

- resources/patch-spinnaker-version.yml
Event
```
{
"version": "2.36.0"
}
```
> chore(cd): update Spinnaker version to 2.36.0
